version: "3.8"

services:
  nodered:
    image: nodered/node-red:((PEP_IMAGE_VERSION))
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    environment:
      - TZ=UTC
    # This is just an example, the volumes section is actually optional
    # PEP will automatically inject the volumes into the container based on the configuration.configs entries
    volumes:
      - nodered_data:/data

volumes:
  nodered_data:
    driver: local

networks:
  default:
    driver: bridge
