version: "3.8"

services:
  nodered:
    # PEP replaces ((PEP_IMAGE_VERSION)) with user-selected version before deployment
    image: nodered/node-red:((PEP_IMAGE_VERSION))
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    environment:
      - TZ=UTC
    # Named volume for persistent Node-RED data
    # Configuration file bind mounts are added via docker-compose.override.yml
    # See: apps/node-red/docker-compose.override.yml for example of PEP-generated overrides
    volumes:
      - nodered_data:/data

volumes:
  nodered_data:
    driver: local

networks:
  default:
    driver: bridge
